### ISSUE TITLE
Allow returning raw payload 

### ISSUE THREAD

**Issue by rebaz94** [Gerrel/firebase_auth_token#1]
Hi, Thanks for your library.

It will be great if we have a new function to return raw data, so that anyone can parse the payload manually.
if you are interested, I can make PR.

Thank you

**Comment by Gerrel** [comment]
Are you missing some data in the user object that is returned?

**Comment by rebaz94** [comment]
Yes, I can't access my custom claim, if I get the payload then I will parse values that I need

**Comment by Gerrel** [comment]
Ah yes indeed this data should be included. Send me a PR and I will check it.

**Comment by rebaz94** [comment]
I'm thinking of just creating a new function that return the payload and use the existing function ```getUserFromToken```

**Comment by rebaz94** [comment]
I created a [PR](https://github.com/Gerrel/firebase_auth_token/pull/2). please check it

**Comment by Gerrel** [comment]
@rebaz94 I've solved the issue by adding method "getCustomClaim" to the user object. I've released v1.0.2

**Comment by rebaz94** [comment]
@Gerrel Thats not solve the problem!, why I call ```getCustomClaim``` multiple times just to get the value?! if you do it anyway, you should make the ```_data``` field public because in my case I'm creating my own ```AuthUser``` and with that I can't do it

**Comment by Gerrel** [comment]
@rebaz94 check the readme. there is now access to the raw data.

**Comment by rebaz94** [comment]
Great, thanks you so much
